kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

namespace: elastic-stack-logging

resources:
- configs
- security_configs
- pdb.yaml
- rbac.yaml
- service.yaml
- sts.yaml
- index-templates
- storageclass.yaml
- certs.yaml
- ism-policies
- alerts
- notifications
- bootstrap.yaml
- p1as-bootstrap.yaml

configMapGenerator:
- files:
  - p1as-bootstrap-resources.yaml
  name: p1as-bootstrap-resources
