apiVersion: apps/v1
kind: Deployment
metadata:
  name: healthcheck-pingaccess-was
  namespace: health
$patch: delete

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: healthcheck-httpbin-pa-was
  namespace: health
$patch: delete

---

apiVersion: v1
kind: Service
metadata:
  name: healthcheck-httpbin-pa-was
  namespace: health
$patch: delete

---