apiVersion: apps/v1
kind: Deployment
metadata:
  name: pingcloud-healthcheck
  namespace: ${PING_CLOUD_NAMESPACE}
$patch: delete

---

apiVersion: v1
kind: Service
metadata:
  name: healthcheck
  namespace: ${PING_CLOUD_NAMESPACE}
$patch: delete

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: healthcheck-ingress
  namespace: ${PING_CLOUD_NAMESPACE}
$patch: delete

---
